apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-deploy
  labels:
    app: pause-app
spec:
  selector:
    matchLabels:
      app: pause-app
  replicas: 500 
  template:
    metadata:
      labels:
        app: pause-app
    spec:
      containers:
      - name: pause-container
        image: "gcr.io/google_containers/pause-ppc64le:3.0"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
